### ISSUE TITLE
Version 0.2.2 for MAC64 is a downloaded text file

### ISSUE THREAD

**Issue by dimified** [operasoftware/operachromiumdriver#13]
The following link includes the version 0.2.2 for MAC 64 but in a text document format which can not be used as an executable file: https://github.com/operasoftware/operachromiumdriver/releases/download/v0.2.2/operadriver_mac64.zip

**Comment by joeyparrish** [comment]
Just passing by, but I clicked that link and got a zip file containing one OSX executable called "operadriver".

**Comment by wladzynski** [comment]
Links for both 0.2.2 and the latest release server proper zip archive for me. Please report back it the issue persists.

**Comment by dimified** [comment]
Alright. Thanks, i will try it out again.
