### ISSUE TITLE
Multiple handles for a single window

### ISSUE THREAD

**Issue by florentbr** [operasoftware/operachromiumdriver#15]
Since Opera 31, the driver returns multiple handles for a single window.

Environment:
Windows 8.1 Selenium 2.47.1 Opera 31.0

To reproduce:

```
from selenium import webdriver

wd = webdriver.Opera()
for handle in wd.window_handles:
    print handle
```

Output:
 CDwindow-25975684-31B7-4521-9A4F-4F5B50988B42
 CDwindow-27057524-E8DB-4708-9092-3E67A0D9B9DB
 CDwindow-182DB55E-624A-4D1F-9F4E-3180CF8EC596

**Comment by jjrodriguez01** [comment]
i get the same issue in selenium 2 and java with operawebdriver anyone knows why?

**Comment by wladzynski** [comment]
Hi @florentbr!
I have tried to reproduce your issue with OperaDriver 2.32 and Opera 49.0.2725.34  and it seems to be working as expected. Window handles contains correct number of handles. 
Please reopen or resubmit the issue if it occurs again.
