### ISSUE TITLE
Dead end?

### ISSUE THREAD

**Issue by qqilihq** [operasoftware/operachromiumdriver#28]
Is this project still maintained? Obviously, the driver does not work with recent Opera versions (see #27).

If there is no more maintenance, it would be really helpful to have an obvious hint in the README.

**Comment by lkende** [comment]
As I mentioned in #27 you can use chromedriver and point to the opera binary and get it work.  I have all the latest Opera versions working in this way.

**Comment by qqilihq** [comment]
Thank you Luke. I replied in #27, will give it a further try and get back!

**Comment by wladzynski** [comment]
Hi! Good news guy! Operadriver has been just updated. Please verify if this solves the issue you were experiencing. We have plans to regularly update this repository with new updated operadriver binaries.

**Comment by qqilihq** [comment]
@wladzynski Great, I'll give it a try and let you know! Thanks.

**Comment by wladzynski** [comment]
I am assuming, that a lack of further activity in this issue means, everything is working fine now. Closing.

**Comment by qqilihq** [comment]
Works like a charm! Apologies for the late feedback and thank you!!
