### ISSUE TITLE
Unable to do automation on Opera Browser

### ISSUE THREAD

**Issue by sanojqa** [operasoftware/operachromiumdriver#32]
OS:
Windows 7
Selenium Version:
3.0.1
Browser:
Opera

Browser Version:
42.0.2393.94

Issue:

I can launch Opera browser but unable to load the URL before that the opera browser got crashed. Following are my code for the execution and reproduce the issue:

System.setProperty("webdriver.opera.driver", operaChromiumDriver);
ChromeOptions options = new ChromeOptions();
options.setBinary(operaBrowserLocation);

	DesiredCapabilities capabilities = new DesiredCapabilities();
	capabilities.setCapability(ChromeOptions.CAPABILITY, options);

	System.out.println(capabilities);

	WebDriver browser = new OperaDriver(capabilities); //Got Crash in this step

	WebDriver driver = browser;
	driver.get("https://in.yahoo.com/");

**Comment by kriegaex** [comment]
I have the same problem with using the Opera Chromium Driver via Geb: Opera 42 gets started, but the `OperaDriver()` constructor never terminates. The open browser itself works nicely though, if I do anything manually in there. The console log says:

```
Starting OperaDriver 0.2.0 (ba47709ed9e35ce26dbd960fb5d75be104290d96) on port 10772
Only local connections are allowed.
Feb 03, 2017 1:40:46 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFORMATION: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
```

Then I have to kill my Geb test process manually.

**Comment by sanojqa** [comment]
Anyone recently executed the automation scripts on Opera browser?

**Comment by lkende** [comment]
Yes, all the time.  I have comments on other issues describing how to do so.

**Comment by kriegaex** [comment]
@lkende, was that remark meant for me or @sanojqa? Am I doing anything wrong? What should I do in order to make it work?

**Comment by wladzynski** [comment]
Hi All!
Please verify whether the latests release solves the issue for you. Thanks in advance!

**Comment by kriegaex** [comment]
@wladzynski: I volunteer to test, but please first give me a reason to do so. Has anything specific been done in order to fix the issue?

**Comment by wladzynski** [comment]
Glad to hear that 👍  I hope it continues to work this way :)
