### ISSUE TITLE
writing cookie on another domain than current page doesn't throw UnknownServerException

### ISSUE THREAD

**Issue by chaby1** [operasoftware/operachromiumdriver#4]
Hi,

This is a minor issue but most of drivers do it (chrome driver for e.g). Of course, there is no reason to do this (except mistake !) but it would be more consistent with other drivers if it would be implemented.

Thanks.

**Comment by emakiej** [comment]
Hi, @chaby1 
For the following testcase:
```python
driver.get("http://www.google.pl")
driver.add_cookie({'name':'TEST_COOKIE', 'value':'Opera', 'domain':'appium-test.prv.pl'})
```
I get
```
selenium.common.exceptions.WebDriverException: Message: invalid cookie domain: invalid domain:"appium-test.prv.pl"
```
for both OperaDriver and ChromeDriver.

As OperaDriver derives from ChromeDriver and this behaviour also is derived we don't concern this issue a bug. Therefore I'm closing it - please reopen if you have a test case which works properly with ChromeDriver and doesn't work with OperaDriver

**Comment by chaby1** [comment]
Hi @emakiej,

In fact, I discover that you need first to send a cookie with correct data. And then send a new cookie with a fake domain to don't throw an exception. But strangely, I can now also reproduce it with ChromeDriver (which was not the case previously, I probably mix some stuff...).

So you might be able to reproduce it with the following : 
````python
# First send a correct cookie.
driver.get("http://www.google.pl")
driver.add_cookie({'name':'TEST_COOKIE', 'value':'Opera', 'domain':'google.pl'})

# Refresh page and send a new cookie, but with a wrong domain. It would not throw an exception...
driver.get("http://www.google.pl")
driver.add_cookie({'name':'TEST_COOKIE', 'value':'Opera', 'domain':'appium-test.prv.pl'})
````
So I suppose we could keep this issue closed and open a new one in ChromeDriver.
