### ISSUE TITLE
Is Opera Yandex supposed to be disabled?

### ISSUE THREAD

**Issue by ramsenc** [operasoftware/operachromiumdriver#43]
The Opera Yandex browsing protection feature does not seem to exist during selenium script runs, but manually it will detect potentially malicious websites. Is this intentional and if so is there a way I can enable Yandex?

Here is what the warning looks like
![2017-08-04_16h08_17](https://user-images.githubusercontent.com/12567147/28990128-2f8143d4-792f-11e7-8390-22a1cf992fbb.png)

**Comment by wladzynski** [comment]
Hi @ramsenc!
Thanks for your report. This behaviour is indeed incorrect. It has been already mentioned in #40.

**Comment by wladzynski** [comment]
Hi @ramsenc!
We have been able to identify the reason, why the fraud protection has not been working in scenario you have described. Please see #40 for detailed answer and an example showing how to prepare a test, which will enable checking a site against the fraud protection mechanism in Opera.
