### ISSUE TITLE
Drive Opera Developer?

### ISSUE THREAD

**Issue by dylancaponi** [operasoftware/operachromiumdriver#49]
Is it possible to drive the developer version of Opera with operachromiumdriver?

Is this a configuration I can change or would a totally different version of operachromiumdriver be required?

**Comment by wladzynski** [comment]
Hi @dylancaponi!
In most cases the latests operadriver release should work just fine with Opera from developer stream. In rare case, developer stream introduces changes, which indeed might break the compatibility with previously released drivers. If such situation occurs, please file an issue and we will try to find a solution then.

**Comment by dylancaponi** [comment]
Yes but... how?  Where is that actual configuration to use the developer version set?

**Comment by wladzynski** [comment]
Hi @dylancaponi!
Please try approach showed in this gist: https://gist.github.com/wladzynski/7ba73492f7493cdd9fa9369050473d20

**Comment by dylancaponi** [comment]
Thank you!  This worked with the binary path set to:
'/Applications/Opera Developer.app/Contents/MacOS/Opera'
