### ISSUE TITLE
Invalid --log-level value 

### ISSUE THREAD

**Issue by markleavesley** [operasoftware/operachromiumdriver#55]
I'm getting the below trying to use Selenium against Opera on Windows 10 x64 Pro (build 17134). Opera version is 53.0.2907.99, Selenium.Chrome.WebDriver (nuget) 2.38.0 and the latest OperaDriver off this site as of today. Coding in VS 2017, C# 7, .NET 4.7.1, console.

```
Starting OperaDriver 2.36 (bf69a2a4687a45dedaabd6155fd52bb0b7eb10c5) on port 24708
Only local connections are allowed.
Starting OperaDriver 2.36 (bf69a2a4687a45dedaabd6155fd52bb0b7eb10c5) on port 9515
Only local connections are allowed.
Invalid --log-level value.
Unable to initialize logging. Exiting...
```
I cannot find a single article that mentions "Invalid --log-level value" that doesn't also involve networking (usually nodemanager).

I tried setting all the log levels to "WARN", i.e.

```
options.SetLoggingPreference(LogType.Browser, LogLevel.Warning);
```

but it made no difference. Also tried both the 32-bit and 64-bit versions of the driver. I do wonder if the double "Starting..." has anything to do with this. My current code is:

```
var options = new OperaOptions
{
    BinaryLocation = Path.Combine(Environment.CurrentDirectory, "operadriver.exe"),
};
using (var driver = new OperaDriver(options))
{
    ...
}
```

Thanks.

**Comment by dmssargent** [comment]
This error seems to arise when operadriver thinks it is Opera itself, so it tries to launch itself as Opera. Try setting the property `webdriver.opera.binary` to something along the lines of `C:\Program Files\Opera\launcher.exe`.

When operadriver opens Opera, one of the arguments it passes is `--log-level=0`, and `0` is not in the set of valid options for the log-level of operadriver, hence operadriver is logging it as the failure message it thinks is actually coming from Opera.

**Comment by markleavesley** [comment]
That does indeed work, thanks!
