### ISSUE TITLE
Opera launching

### ISSUE THREAD

**Issue by PetPython** [operasoftware/operachromiumdriver#58]
Does the last driver update for Opera work correctly for everyone?
Using the dektop.py guide along with some of tips from local commenters, here is the whole code I managed:

    from selenium import webdriver
    from selenium.webdriver.chrome import service

    webdriver_service = service.Service(r'C:\Program Files (x86)\Opera\operadriver_win64\operadriver.exe')
    webdriver_service.start()

    options = webdriver.ChromeOptions()
    options.binary_location = r'C:\Program Files (x86)\Opera\launcher.exe'

    driver = webdriver.Remote(webdriver_service.service_url, webdriver.DesiredCapabilities.OPERA, options = options)

    driver.get('http://www.google.com')

This leads to start of Opera, but instead of an asked page it opens a blank one named **data:,**
The terminal says **Opera failed to start: exited normally** and **The process started from Opera location is no longer running, so OperaDriver is assuming that Opera has crashed**.
Even more, the webdriver console says **Wrong definition of keybinding**, **Keybindings Shift+/ used for both command Find and Find**, and **Error dxva_video_decode_accelerator_win.cc** which I have no idea how is even related to the problem.

**Comment by bgmafia** [comment]
You should make sure that you are pointing to the [latest](https://github.com/operasoftware/operachromiumdriver/releases) release of the webdriver (currently it is 2.42).
Also you should navigate the binary_location to opera.exe and not launcher.exe atleast for me that was causing the issue.

**Comment by PetPython** [comment]
Damn, you are actually right.
The whole problem was in starting from **launcher.exe**. Selecting the path to **opera.exe** (which lies in version sub-folder of main Opera folder) allows to work with the browser as it should be.
Much appreciate for pointing that out. Goodbye, Chrome webdriver!

**Comment by PolinaLyzenkova** [comment]
@bgmafia and @PetPython   Bless you for this comments!
