### ISSUE TITLE
Error Opera failed to start: exited normally (unknown error: DevToolsActivePort file doesn't exist)

### ISSUE THREAD

**Issue by range36rus** [operasoftware/operachromiumdriver#66]
Hi.
I use Opera v. 60.0.3255.83 and Opera Chromium Driver v. 2.45. I try start test Selenium, using this code (java):
```
// System.setProperty("webdriver.opera.driver","operadriver.exe");    
OperaOptions options = new OperaOptions();
options.setBinary("C:\\Users\\admin_test\\AppData\\Local\\Programs\\Opera\\launcher.exe");
options.setExperimentalOption("useAutomationExtension", false);
WebDriver driver = new OperaDriver(options);
```

My operadriver.exe writed in system variable PATH.
When I run, I get the error:

> org.openqa.selenium.WebDriverException: unknown error: Opera failed to start: exited normally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Users\admin_test\AppData\Local\Programs\Opera\launcher.exe is no longer running, so OperaDriver is assuming that Opera has crashed.)
  (Driver info: OperaDriver=2.45.3255 (O60),platform=Windows NT 10.0.17763 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.21 seconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'LAPTOP-GOG9SDSJ', ip: '169.254.82.138', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: driver.version: OperaDriver

Please, say me, how correct this error? Thanks :)

**Comment by range36rus** [comment]
Good, I invented solution on this problem. I reinstalled opera in default path (C:\Program Files\Opera) and setted option installs (install for all users). Now all working.

**Comment by range36rus** [comment]
This problem is observed on Windows 7! On Windows 10, it is not.

**Comment by EkS2018** [comment]
> This problem is observed on Windows 7! On Windows 10, it is not.

I have the same problem on Windows 10
