### ISSUE TITLE
Released binaries contain version number and platform name in file name

### ISSUE THREAD

**Issue by jimevans** [operasoftware/operachromiumdriver#7]
Currently the binary contained in operadriver-0.1.0-win32.zip is operadriver-0.1.0-win32.exe. This makes it nearly impossible for language bindings to create a consistent OperaDriver class that can launch the driver executable without either (1) forcing the user to pass in the file name, which is inconsistent with every other implementation currently available; or (2) forcing the language bindings to release a revision with any new release of the driver executable. A better approach would be to have the executable name within the downloadable archives to be a consistent name across versions and platforms.

**Comment by emakiej** [comment]
Hi, @jimevans . Thanks for the remark! We've adjusted files names for executables as well as for the archives (analogously to the ChromeDriver).
